### ISSUE TITLE
Mayfly_Logger PCB in Europe

### ISSUE THREAD

**Issue by dkalog** [EnviroDIY/EnviroDIY_Mayfly_Logger#19]
Hi ,

I am trying having access to MayFly Logger from some place in Europe either in NL or Greece. According to Amazon.com this is not possible. This leaves me with two options: a) either get the PCB from some place and solder the BOM myself on the PCB or b) getting the gerber/eagle  files and print them to PCB locally or c) the long way  going from the semantics --> PCB and then to the final product.  What do you suggest ?

**Comment by SRGDamia1** [comment]
I don't think there's currently any way direct way to get a Mayfly shipped anywhere except in the US.  The schematics are available, but the gerber/eagle files aren't and I doubt they'll ever be shared freely.  @s-hicks2 might know more.

While I think the Mayfly is quite nice, I would guess that it would be much, much easier for you to look into Mayfly alternatives than to try to manually solder something together.  The original Mayfly is very similar to the Sodaq Mbili.  Sodaq is based in the Netherlands, so I imagine you could get their products shipped to you.
