### ISSUE TITLE
Value of C2 

### ISSUE THREAD

**Issue by dkalog** [EnviroDIY/EnviroDIY_Mayfly_Logger#25]
Hi , 
It seems that I have destroyed C2 . According to schematics, it  seems to be 100uF. Is this correct ? I couldn't locate an SMD with 100uF.

**Comment by SRGDamia1** [comment]
@s-hicks2 ?

**Comment by s-hicks2** [comment]
Yes, it is a 100uf polarized cap, the exact part number is TAJB107M010RNJ.
